version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: satu-peta-api
    restart: unless-stopped
    ports:
      - "5000:5000"
    env_file:
      - environment.env
    command: uvicorn app.main:app --host 0.0.0.0 --port 5000 --reload
