"""revision table

Revision ID: ea436d811762
Revises: a5dcbea2c0a5
Create Date: 2025-09-15 13:06:38.967975

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = "ea436d811762"
down_revision: Union[str, None] = "a5dcbea2c0a5"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "article_comments",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("article_id", sa.Integer(), nullable=False),
        sa.Column("article_slug", sa.String(length=256), nullable=False),
        sa.Column("comment", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_article_comments_article_id"), "article_comments", ["article_id"], unique=False)
    op.create_index(op.f("ix_article_comments_article_slug"), "article_comments", ["article_slug"], unique=False)
    op.add_column("articles", sa.Column("id", sa.Integer(), autoincrement=True, nullable=False))
    op.drop_column("articles", "article_id")
    # op.alter_column('businesses_service', 'update_at',
    #            existing_type=mysql.CHAR(charset='utf8mb3', collation='utf8mb3_general_ci', length=16),
    #            type_=sa.DateTime(),
    #            nullable=True)
    # op.alter_column('forestry', 'fore_kps_id',
    #            existing_type=mysql.CHAR(charset='utf8mb3', collation='utf8mb3_general_ci', length=11),
    #            type_=sa.Integer(),
    #            existing_nullable=False,
    #            autoincrement=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "forestry",
        "fore_kps_id",
        existing_type=sa.Integer(),
        type_=mysql.CHAR(charset="utf8mb3", collation="utf8mb3_general_ci", length=11),
        existing_nullable=False,
        autoincrement=False,
    )
    op.alter_column(
        "businesses_service",
        "update_at",
        existing_type=sa.DateTime(),
        type_=mysql.CHAR(charset="utf8mb3", collation="utf8mb3_general_ci", length=16),
        nullable=False,
    )
    op.add_column("articles", sa.Column("article_id", mysql.INTEGER(), autoincrement=True, nullable=False))
    op.drop_column("articles", "id")
    op.drop_index(op.f("ix_article_comments_article_slug"), table_name="article_comments")
    op.drop_index(op.f("ix_article_comments_article_id"), table_name="article_comments")
    op.drop_table("article_comments")
    # ### end Alembic commands ###
