"""revision table

Revision ID: a5dcbea2c0a5
Revises: 099536a084e5
Create Date: 2025-09-15 08:00:26.606153

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = "a5dcbea2c0a5"
down_revision: Union[str, None] = "099536a084e5"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # op.alter_column('businesses_service', 'update_at',
    #            existing_type=mysql.CHAR(charset='utf8mb3', collation='utf8mb3_general_ci', length=16),
    #            type_=sa.DateTime(),
    #            nullable=True)
    # Do NOT alter 'fore_kps_id' to allow NULLs if it's a PRIMARY KEY (see MySQL error 1171).
    # If you need to change the type, ensure nullable=False is set.
    # op.alter_column(
    #     "forestry",
    #     "fore_kps_id",
    #     existing_type=mysql.CHAR(charset="utf8mb3", collation="utf8mb3_general_ci", length=11),
    #     type_=sa.Integer(),
    #     autoincrement=False,
    #     nullable=False,  # Ensure NOT NULL for PRIMARY KEY
    # )
    op.alter_column(
        "forestry",
        "reg_id",
        existing_type=mysql.CHAR(charset="utf8mb3", collation="utf8mb3_general_ci", length=10),
        nullable=True,
    )
    op.alter_column(
        "forestry",
        "fore_skema_id",
        existing_type=mysql.CHAR(charset="utf8mb3", collation="utf8mb3_general_ci", length=4),
        nullable=True,
    )
    op.alter_column("forestry", "kph_acc_id", existing_type=mysql.CHAR(length=36), nullable=True)
    op.alter_column("forestry", "fore_kh_id", existing_type=mysql.JSON(), nullable=True)
    op.alter_column("forestry", "fore_luas", existing_type=mysql.FLOAT(precision=10, scale=2), nullable=True)
    op.alter_column("forestry", "fore_jumlah_kk", existing_type=mysql.INTEGER(), nullable=True)
    op.alter_column(
        "forestry",
        "fore_nama_ketua",
        existing_type=mysql.VARCHAR(charset="utf8mb3", collation="utf8mb3_general_ci", length=256),
        nullable=True,
    )
    op.alter_column(
        "forestry",
        "fore_kontak_ketua",
        existing_type=mysql.CHAR(charset="utf8mb3", collation="utf8mb3_general_ci", length=16),
        nullable=True,
    )
    op.alter_column(
        "forestry",
        "fore_peta_ps",
        existing_type=mysql.VARCHAR(charset="utf8mb3", collation="utf8mb3_general_ci", length=256),
        nullable=True,
    )
    op.alter_column(
        "forestry",
        "fore_pps_vertek",
        existing_type=mysql.CHAR(charset="utf8mb3", collation="utf8mb3_general_ci", length=4),
        nullable=True,
    )
    op.alter_column(
        "forestry",
        "fore_pps_sknagari",
        existing_type=mysql.VARCHAR(charset="utf8mb3", collation="utf8mb3_general_ci", length=256),
        nullable=True,
    )
    op.alter_column(
        "forestry",
        "fore_sk_bupati",
        existing_type=mysql.VARCHAR(charset="utf8mb3", collation="utf8mb3_general_ci", length=256),
        nullable=True,
    )
    op.alter_column(
        "forestry",
        "fore_pps_valid",
        existing_type=mysql.ENUM("Y", "N", charset="utf8mb3", collation="utf8mb3_general_ci"),
        nullable=True,
        existing_server_default=sa.text("'N'"),
    )
    op.alter_column("forestry", "fore_pps_klhk", existing_type=mysql.CHAR(length=4), nullable=True)
    op.alter_column(
        "forestry",
        "fore_kps_valid",
        existing_type=mysql.ENUM("Y", "N", charset="utf8mb3", collation="utf8mb3_general_ci"),
        nullable=True,
        existing_server_default=sa.text("'N'"),
    )
    op.alter_column("forestry", "create_by", existing_type=mysql.CHAR(length=36), nullable=True)
    op.alter_column(
        "forestry",
        "create_at",
        existing_type=mysql.DATETIME(),
        nullable=True,
        existing_server_default=sa.text("CURRENT_TIMESTAMP"),
    )
    op.alter_column(
        "komoditas",
        "komoditas_nama",
        existing_type=mysql.VARCHAR(charset="utf8mb3", collation="utf8mb3_general_ci", length=256),
        nullable=True,
    )
    op.alter_column(
        "komoditas",
        "komoditas_jenis",
        existing_type=mysql.CHAR(charset="utf8mb3", collation="utf8mb3_general_ci", length=8),
        nullable=True,
    )
    op.alter_column(
        "komoditas",
        "komoditas_status",
        existing_type=mysql.ENUM("Y", "N", charset="utf8mb3", collation="utf8mb3_general_ci"),
        nullable=True,
        existing_server_default=sa.text("'N'"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "komoditas",
        "komoditas_status",
        existing_type=mysql.ENUM("Y", "N", charset="utf8mb3", collation="utf8mb3_general_ci"),
        nullable=False,
        existing_server_default=sa.text("'N'"),
    )
    op.alter_column(
        "komoditas",
        "komoditas_jenis",
        existing_type=mysql.CHAR(charset="utf8mb3", collation="utf8mb3_general_ci", length=8),
        nullable=False,
    )
    op.alter_column(
        "komoditas",
        "komoditas_nama",
        existing_type=mysql.VARCHAR(charset="utf8mb3", collation="utf8mb3_general_ci", length=256),
        nullable=False,
    )
    op.alter_column(
        "forestry",
        "create_at",
        existing_type=mysql.DATETIME(),
        nullable=False,
        existing_server_default=sa.text("CURRENT_TIMESTAMP"),
    )
    op.alter_column("forestry", "create_by", existing_type=mysql.CHAR(length=36), nullable=False)
    op.alter_column(
        "forestry",
        "fore_kps_valid",
        existing_type=mysql.ENUM("Y", "N", charset="utf8mb3", collation="utf8mb3_general_ci"),
        nullable=False,
        existing_server_default=sa.text("'N'"),
    )
    op.alter_column("forestry", "fore_pps_klhk", existing_type=mysql.CHAR(length=4), nullable=False)
    op.alter_column(
        "forestry",
        "fore_pps_valid",
        existing_type=mysql.ENUM("Y", "N", charset="utf8mb3", collation="utf8mb3_general_ci"),
        nullable=False,
        existing_server_default=sa.text("'N'"),
    )
    op.alter_column(
        "forestry",
        "fore_sk_bupati",
        existing_type=mysql.VARCHAR(charset="utf8mb3", collation="utf8mb3_general_ci", length=256),
        nullable=False,
    )
    op.alter_column(
        "forestry",
        "fore_pps_sknagari",
        existing_type=mysql.VARCHAR(charset="utf8mb3", collation="utf8mb3_general_ci", length=256),
        nullable=False,
    )
    op.alter_column(
        "forestry",
        "fore_pps_vertek",
        existing_type=mysql.CHAR(charset="utf8mb3", collation="utf8mb3_general_ci", length=4),
        nullable=False,
    )
    op.alter_column(
        "forestry",
        "fore_peta_ps",
        existing_type=mysql.VARCHAR(charset="utf8mb3", collation="utf8mb3_general_ci", length=256),
        nullable=False,
    )
    op.alter_column(
        "forestry",
        "fore_kontak_ketua",
        existing_type=mysql.CHAR(charset="utf8mb3", collation="utf8mb3_general_ci", length=16),
        nullable=False,
    )
    op.alter_column(
        "forestry",
        "fore_nama_ketua",
        existing_type=mysql.VARCHAR(charset="utf8mb3", collation="utf8mb3_general_ci", length=256),
        nullable=False,
    )
    op.alter_column("forestry", "fore_jumlah_kk", existing_type=mysql.INTEGER(), nullable=False)
    op.alter_column("forestry", "fore_luas", existing_type=mysql.FLOAT(precision=10, scale=2), nullable=False)
    op.alter_column("forestry", "fore_kh_id", existing_type=mysql.JSON(), nullable=False)
    op.alter_column("forestry", "kph_acc_id", existing_type=mysql.CHAR(length=36), nullable=False)
    op.alter_column(
        "forestry",
        "fore_skema_id",
        existing_type=mysql.CHAR(charset="utf8mb3", collation="utf8mb3_general_ci", length=4),
        nullable=False,
    )
    op.alter_column(
        "forestry",
        "reg_id",
        existing_type=mysql.CHAR(charset="utf8mb3", collation="utf8mb3_general_ci", length=10),
        nullable=False,
    )
    op.alter_column(
        "forestry",
        "fore_kps_id",
        existing_type=sa.Integer(),
        type_=mysql.CHAR(charset="utf8mb3", collation="utf8mb3_general_ci", length=11),
        existing_nullable=False,
        autoincrement=False,
    )
    op.alter_column(
        "businesses_service",
        "update_at",
        existing_type=sa.DateTime(),
        type_=mysql.CHAR(charset="utf8mb3", collation="utf8mb3_general_ci", length=16),
        nullable=False,
    )
    # ### end Alembic commands ###
